### ISSUE TITLE
Incompatible numpy dependency vs. build123d 0.8.0

### ISSUE THREAD

**Issue by pmuller** [bernhard-42/jupyter-cadquery#113]
build123d 0.8.0 now requires numpy `>=2,<3`, but some of jupyter-cadquery's dependencies seem to require numpy `<2`:

```
$ jcv
[JCV] Creating a Jupyter kernel specification called 'jcv' for this conda environment
Installed kernelspec jcv in /home/foo/.local/share/jupyter/kernels/jcv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".venv/lib/python3.12/site-packages/jupyter_cadquery/__init__.py", line 34, in <module>
    from .ocp_utils import occt_version
  File ".venv/lib/python3.12/site-packages/jupyter_cadquery/ocp_utils.py", line 14, in <module>
    from cadquery import Compound, Location, Color
  File ".venv/lib/python3.12/site-packages/cadquery/__init__.py", line 22, in <module>
    from .occ_impl import exporters
  File ".venv/lib/python3.12/site-packages/cadquery/occ_impl/exporters/__init__.py", line 10, in <module>
    from ...cq import Workplane
  File ".venv/lib/python3.12/site-packages/cadquery/cq.py", line 62, in <module>
    from .sketch import Sketch
  File ".venv/lib/python3.12/site-packages/cadquery/sketch.py", line 28, in <module>
    from .occ_impl.sketch_solver import (
  File ".venv/lib/python3.12/site-packages/cadquery/occ_impl/sketch_solver.py", line 3, in <module>
    from nptyping import NDArray as Array
  File ".venv/lib/python3.12/site-packages/nptyping/__init__.py", line 30, in <module>
    from nptyping.ndarray import NDArray
  File ".venv/lib/python3.12/site-packages/nptyping/ndarray.py", line 32, in <module>
    from nptyping.shape_expression import (
  File ".venv/lib/python3.12/site-packages/nptyping/shape_expression.py", line 35, in <module>
    from nptyping.typing_ import Literal
  File ".venv/lib/python3.12/site-packages/nptyping/typing_.py", line 66, in <module>
    Bool8: TypeAlias = np.bool8
                       ^^^^^^^^
  File ".venv/lib/python3.12/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?
```

For reference:
```
$ uv tree
cad v0.1.0
├── build123d v0.8.0
│   ├── anytree v2.12.1
│   │   └── six v1.16.0
│   ├── cadquery-ocp v7.7.2
│   ├── ezdxf v1.3.4
│   │   ├── fonttools v4.55.0
│   │   ├── numpy v2.0.2
│   │   ├── pyparsing v3.2.0
│   │   └── typing-extensions v4.12.2
│   ├── ipython v8.30.0
│   │   ├── decorator v5.1.1
│   │   ├── jedi v0.19.2
│   │   │   └── parso v0.8.4
│   │   ├── matplotlib-inline v0.1.7
│   │   │   └── traitlets v5.14.3
│   │   ├── pexpect v4.9.0
│   │   │   └── ptyprocess v0.7.0
│   │   ├── prompt-toolkit v3.0.48
│   │   │   └── wcwidth v0.2.13
│   │   ├── pygments v2.18.0
│   │   ├── stack-data v0.6.3
│   │   │   ├── asttokens v3.0.0
│   │   │   ├── executing v2.1.0
│   │   │   └── pure-eval v0.2.3
│   │   └── traitlets v5.14.3
│   ├── numpy v2.0.2
│   ├── ocpsvg v0.3.1
│   │   ├── cadquery-ocp v7.7.2
│   │   └── svgelements v1.9.6
│   ├── py-lib3mf v2.3.1
│   ├── svgpathtools v1.6.1
│   │   ├── numpy v2.0.2
│   │   ├── scipy v1.14.1
│   │   │   └── numpy v2.0.2
│   │   └── svgwrite v1.4.3
│   ├── trianglesolver v1.2
│   └── typing-extensions v4.12.2
├── cadquery v2.4.0
│   ├── cadquery-ocp v7.7.2
│   ├── casadi v3.6.7
│   │   └── numpy v2.0.2
│   ├── ezdxf v1.3.4 (*)
│   ├── multimethod v1.9.1
│   ├── nlopt v2.9.0
│   │   └── numpy v2.0.2
│   ├── nptyping v2.0.1
│   │   └── numpy v2.0.2
│   ├── path v17.0.0
│   └── typish v1.9.3
├── jupyter-cadquery v3.5.2
│   ├── cachetools v5.2.1
│   ├── cad-viewer-widget v1.4.1
│   │   ├── ipywidgets v7.8.5
│   │   │   ├── comm v0.2.2
│   │   │   │   └── traitlets v5.14.3
│   │   │   ├── ipython v8.30.0 (*)
│   │   │   ├── ipython-genutils v0.2.0
│   │   │   ├── jupyterlab-widgets v1.1.11
│   │   │   ├── traitlets v5.14.3
│   │   │   └── widgetsnbextension v3.6.10
│   │   │       └── notebook v6.5.7
│   │   │           ├── argon2-cffi v23.1.0
│   │   │           │   └── argon2-cffi-bindings v21.2.0
│   │   │           │       └── cffi v1.17.1
│   │   │           │           └── pycparser v2.22
│   │   │           ├── ipykernel v6.29.5
│   │   │           │   ├── comm v0.2.2 (*)
│   │   │           │   ├── debugpy v1.8.9
│   │   │           │   ├── ipython v8.30.0 (*)
│   │   │           │   ├── jupyter-client v7.4.9
│   │   │           │   │   ├── entrypoints v0.4
│   │   │           │   │   ├── jupyter-core v5.7.2
│   │   │           │   │   │   ├── platformdirs v4.3.6
│   │   │           │   │   │   └── traitlets v5.14.3
│   │   │           │   │   ├── nest-asyncio v1.6.0
│   │   │           │   │   ├── python-dateutil v2.9.0.post0
│   │   │           │   │   │   └── six v1.16.0
│   │   │           │   │   ├── pyzmq v26.2.0
│   │   │           │   │   ├── tornado v6.4.2
│   │   │           │   │   └── traitlets v5.14.3
│   │   │           │   ├── jupyter-core v5.7.2 (*)
│   │   │           │   ├── matplotlib-inline v0.1.7 (*)
│   │   │           │   ├── nest-asyncio v1.6.0
│   │   │           │   ├── packaging v24.2
│   │   │           │   ├── psutil v6.1.0
│   │   │           │   ├── pyzmq v26.2.0
│   │   │           │   ├── tornado v6.4.2
│   │   │           │   └── traitlets v5.14.3
│   │   │           ├── ipython-genutils v0.2.0
│   │   │           ├── jinja2 v3.1.4
│   │   │           │   └── markupsafe v3.0.2
│   │   │           ├── jupyter-client v7.4.9 (*)
│   │   │           ├── jupyter-core v5.7.2 (*)
│   │   │           ├── nbclassic v1.1.0
│   │   │           │   ├── ipykernel v6.29.5 (*)
│   │   │           │   ├── ipython-genutils v0.2.0
│   │   │           │   ├── nest-asyncio v1.6.0
│   │   │           │   └── notebook-shim v0.2.4
│   │   │           │       └── jupyter-server v1.24.0
│   │   │           │           ├── anyio v3.7.1
│   │   │           │           │   ├── idna v3.10
│   │   │           │           │   └── sniffio v1.3.1
│   │   │           │           ├── argon2-cffi v23.1.0 (*)
│   │   │           │           ├── jinja2 v3.1.4 (*)
│   │   │           │           ├── jupyter-client v7.4.9 (*)
│   │   │           │           ├── jupyter-core v5.7.2 (*)
│   │   │           │           ├── nbconvert v6.5.4
│   │   │           │           │   ├── beautifulsoup4 v4.12.3
│   │   │           │           │   │   └── soupsieve v2.6
│   │   │           │           │   ├── bleach v6.2.0
│   │   │           │           │   │   └── webencodings v0.5.1
│   │   │           │           │   ├── defusedxml v0.7.1
│   │   │           │           │   ├── entrypoints v0.4
│   │   │           │           │   ├── jinja2 v3.1.4 (*)
│   │   │           │           │   ├── jupyter-core v5.7.2 (*)
│   │   │           │           │   ├── jupyterlab-pygments v0.3.0
│   │   │           │           │   ├── lxml v5.3.0
│   │   │           │           │   │   └── lxml-html-clean v0.4.1 (extra: html-clean)
│   │   │           │           │   │       └── lxml v5.3.0 (*)
│   │   │           │           │   ├── markupsafe v3.0.2
│   │   │           │           │   ├── mistune v0.8.4
│   │   │           │           │   ├── nbclient v0.5.13
│   │   │           │           │   │   ├── jupyter-client v7.4.9 (*)
│   │   │           │           │   │   ├── nbformat v5.10.4
│   │   │           │           │   │   │   ├── fastjsonschema v2.21.0
│   │   │           │           │   │   │   ├── jsonschema v4.23.0
│   │   │           │           │   │   │   │   ├── attrs v24.2.0
│   │   │           │           │   │   │   │   ├── jsonschema-specifications v2024.10.1
│   │   │           │           │   │   │   │   │   └── referencing v0.35.1
│   │   │           │           │   │   │   │   │       ├── attrs v24.2.0
│   │   │           │           │   │   │   │   │       └── rpds-py v0.21.0
│   │   │           │           │   │   │   │   ├── referencing v0.35.1 (*)
│   │   │           │           │   │   │   │   └── rpds-py v0.21.0
│   │   │           │           │   │   │   ├── jupyter-core v5.7.2 (*)
│   │   │           │           │   │   │   └── traitlets v5.14.3
│   │   │           │           │   │   ├── nest-asyncio v1.6.0
│   │   │           │           │   │   └── traitlets v5.14.3
│   │   │           │           │   ├── nbformat v5.10.4 (*)
│   │   │           │           │   ├── packaging v24.2
│   │   │           │           │   ├── pandocfilters v1.5.1
│   │   │           │           │   ├── pygments v2.18.0
│   │   │           │           │   ├── tinycss2 v1.4.0
│   │   │           │           │   │   └── webencodings v0.5.1
│   │   │           │           │   └── traitlets v5.14.3
│   │   │           │           ├── nbformat v5.10.4 (*)
│   │   │           │           ├── packaging v24.2
│   │   │           │           ├── prometheus-client v0.21.0
│   │   │           │           ├── pyzmq v26.2.0
│   │   │           │           ├── send2trash v1.8.3
│   │   │           │           ├── terminado v0.18.1
│   │   │           │           │   ├── ptyprocess v0.7.0
│   │   │           │           │   └── tornado v6.4.2
│   │   │           │           ├── tornado v6.4.2
│   │   │           │           ├── traitlets v5.14.3
│   │   │           │           └── websocket-client v1.8.0
│   │   │           ├── nbconvert v6.5.4 (*)
│   │   │           ├── nbformat v5.10.4 (*)
│   │   │           ├── nest-asyncio v1.6.0
│   │   │           ├── prometheus-client v0.21.0
│   │   │           ├── pyzmq v26.2.0
│   │   │           ├── send2trash v1.8.3
│   │   │           ├── terminado v0.18.1 (*)
│   │   │           ├── tornado v6.4.2
│   │   │           └── traitlets v5.14.3
│   │   ├── jupyterlab v3.5.3
│   │   │   ├── ipython v8.30.0 (*)
│   │   │   ├── jinja2 v3.1.4 (*)
│   │   │   ├── jupyter-core v5.7.2 (*)
│   │   │   ├── jupyter-server v1.24.0 (*)
│   │   │   ├── jupyterlab-server v2.27.3
│   │   │   │   ├── babel v2.16.0
│   │   │   │   ├── jinja2 v3.1.4 (*)
│   │   │   │   ├── json5 v0.10.0
│   │   │   │   ├── jsonschema v4.23.0 (*)
│   │   │   │   ├── jupyter-server v1.24.0 (*)
│   │   │   │   ├── packaging v24.2
│   │   │   │   └── requests v2.32.3
│   │   │   │       ├── certifi v2024.8.30
│   │   │   │       ├── charset-normalizer v3.4.0
│   │   │   │       ├── idna v3.10
│   │   │   │       └── urllib3 v2.2.3
│   │   │   ├── nbclassic v1.1.0 (*)
│   │   │   ├── notebook v6.5.7 (*)
│   │   │   ├── packaging v24.2
│   │   │   ├── tomli v2.2.1
│   │   │   └── tornado v6.4.2
│   │   ├── numpy v2.0.2
│   │   ├── pyparsing v3.2.0
│   │   └── traitlets v5.14.3
│   ├── numpy-quaternion v2024.0.3
│   │   ├── numba v0.60.0
│   │   │   ├── llvmlite v0.43.0
│   │   │   └── numpy v2.0.2
│   │   ├── numpy v2.0.2
│   │   └── scipy v1.14.1 (*)
│   ├── voila v0.3.8
│   │   ├── jupyter-client v7.4.9 (*)
│   │   ├── jupyter-core v5.7.2 (*)
│   │   ├── jupyter-server v1.24.0 (*)
│   │   ├── jupyterlab-server v2.27.3 (*)
│   │   ├── nbclient v0.5.13 (*)
│   │   ├── nbconvert v6.5.4 (*)
│   │   ├── traitlets v5.14.3
│   │   └── websockets v14.1
│   └── webcolors v1.13
├── lxml[html-clean] v5.3.0 (*)
├── basedpyright v1.22.0 (group: dev)
│   └── nodejs-wheel-binaries v22.11.0
└── ruff v0.8.1 (group: dev)
(*) Package tree already displayed
```

**Comment by bernhard-42** [comment]
fyi, I am now working on the integration of the latest viewer capabilities from ocp_vscode and the latest cadquery/build123d.
cad-viewer-widget is ported, now I'll integrate it into jupyter-cadquery.
This will address this issue

**Comment by bernhard-42** [comment]
Solved with 4.0.2 as long as you use cadquery 2.6.0dev (master)
